stages:
- build
- test 
- sonarqube-check

build:
 stage: build
 script:
    - cd BE
    - ./gradlew build -x test
 
test:
  stage: test
  script:
    - cd BE
    - ./gradlew test

sonarqube-check:
  stage: sonarqube-check
  script: 
    - cd BE
    - ./gradlew sonarqube

